tasks:
  - name: Install other system packages
    command: |
      sudo apt-get update
      sudo apt-get install -y uuid-runtime

  - name: Install latest AWS CLI & Set the aws profiles
    command: |
      cd /tmp
      curl -fSsl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip -qq awscliv2.zip
      sudo ./aws/install --update
      rm awscliv2.zip
      [[ -d /home/gitpod/.aws ]] || mkdir /home/gitpod/.aws
      touch /home/gitpod/.aws/config
      tee /home/gitpod/.aws/config << AWSFILE
      [profile default]
      sso_start_url = $AWS_SSO_START_URL
      sso_region = eu-west-1
      sso_account_id = $AWS_ACCOUNT_ID
      sso_role_name = $AWS_SSO_ROLE_NAME
      region = eu-west-1
      AWSFILE

  - init: |
      npm install -g @aws-amplify/cli
    command: amplify version
